"""merchant brand voice fields

Revision ID: 2c335d7cb9b7
Revises: 97362ba0fb6d
Create Date: 2026-06-08 21:41:24.347076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c335d7cb9b7'
down_revision: Union[str, None] = '97362ba0fb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('business_description', sa.Text(), nullable=True))
    op.add_column('merchants', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'system_prompt')
    op.drop_column('merchants', 'business_description')
    op.drop_column('merchants', 'business_type')
    # ### end Alembic commands ###
