"""product context, default identifiers, dm contacts

Revision ID: 7fd501aabf98
Revises: cd4918a4d67e
Create Date: 2026-06-09 02:34:15.796727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7fd501aabf98'
down_revision: Union[str, None] = 'cd4918a4d67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_dm_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_dm_contacts_merchant_id'), 'telegram_dm_contacts', ['merchant_id'], unique=False)
    op.add_column('products', sa.Column('identifier', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_ocr_identified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('telegram_bot_configs', sa.Column('default_product_identifier', sa.Text(), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('default_product_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bot_configs', 'default_product_instructions')
    op.drop_column('telegram_bot_configs', 'default_product_identifier')
    op.drop_column('products', 'is_ocr_identified')
    op.drop_column('products', 'instructions')
    op.drop_column('products', 'identifier')
    op.drop_index(op.f('ix_telegram_dm_contacts_merchant_id'), table_name='telegram_dm_contacts')
    op.drop_table('telegram_dm_contacts')
    # ### end Alembic commands ###
