"""product is_published_to_channel

Revision ID: 932fadba31b3
Revises: 9d639dbf5abd
Create Date: 2026-06-08 23:13:41.631442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '932fadba31b3'
down_revision: Union[str, None] = '9d639dbf5abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_published_to_channel', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_published_to_channel')
    # ### end Alembic commands ###
