"""telegram channel + channel_posts

Revision ID: 9d639dbf5abd
Revises: f8848995428f
Create Date: 2026-06-08 22:24:14.453275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d639dbf5abd'
down_revision: Union[str, None] = 'f8848995428f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channel_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('photo_file_id', sa.String(length=255), nullable=True),
    sa.Column('posted_by_admin', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_channel_message')
    )
    op.create_index(op.f('ix_telegram_channel_posts_merchant_id'), 'telegram_channel_posts', ['merchant_id'], unique=False)
    op.add_column('telegram_bot_configs', sa.Column('channel_id', sa.BigInteger(), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('channel_username', sa.String(length=255), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('channel_title', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'telegram_bot_configs', ['channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_bot_configs', type_='unique')
    op.drop_column('telegram_bot_configs', 'channel_title')
    op.drop_column('telegram_bot_configs', 'channel_username')
    op.drop_column('telegram_bot_configs', 'channel_id')
    op.drop_index(op.f('ix_telegram_channel_posts_merchant_id'), table_name='telegram_channel_posts')
    op.drop_table('telegram_channel_posts')
    # ### end Alembic commands ###
