"""optional price sku + ai agent fields

Revision ID: cd4918a4d67e
Revises: 932fadba31b3
Create Date: 2026-06-09 00:01:11.844165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd4918a4d67e'
down_revision: Union[str, None] = '932fadba31b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('telegram_bot_configs', sa.Column('ai_provider', sa.String(length=20), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('ai_api_key', sa.Text(), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('ai_auto_reply_dm', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('telegram_bot_configs', sa.Column('ai_auto_reply_comments', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('telegram_bot_configs', sa.Column('ai_parse_hashtag_products', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bot_configs', 'ai_parse_hashtag_products')
    op.drop_column('telegram_bot_configs', 'ai_auto_reply_comments')
    op.drop_column('telegram_bot_configs', 'ai_auto_reply_dm')
    op.drop_column('telegram_bot_configs', 'ai_model')
    op.drop_column('telegram_bot_configs', 'ai_api_key')
    op.drop_column('telegram_bot_configs', 'ai_provider')
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###
