"""order payment_account_id + notes

Revision ID: f03b51db6828
Revises: 7fd501aabf98
Create Date: 2026-06-09 17:48:21.039039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f03b51db6828'
down_revision: Union[str, None] = '7fd501aabf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_account_id', sa.Uuid(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'orders', 'merchant_payment_accounts', ['payment_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'payment_account_id')
    # ### end Alembic commands ###
