"""move brand voice to telegram_bot_configs

Revision ID: f8848995428f
Revises: 2c335d7cb9b7
Create Date: 2026-06-08 21:57:49.260864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8848995428f'
down_revision: Union[str, None] = '2c335d7cb9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'system_prompt')
    op.drop_column('merchants', 'business_type')
    op.drop_column('merchants', 'business_description')
    op.add_column('telegram_bot_configs', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('business_description', sa.Text(), nullable=True))
    op.add_column('telegram_bot_configs', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bot_configs', 'system_prompt')
    op.drop_column('telegram_bot_configs', 'business_description')
    op.drop_column('telegram_bot_configs', 'business_type')
    op.add_column('merchants', sa.Column('business_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
